version: '2'
services:
  db:
    build: ./postgres
    environment:
        - DB_NAME=mydb
    expose:
      - "5432"
    networks:
      my_network:
        aliases:
          - mydb
  httpServer:
    image: maven:3-alpine
    command: mvn exec:java
    volumes:
        - .:/opt/app
    working_dir: /opt/app
    environment:
        - MAVEN_OPTS= -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
        - APP_STRATEGY=GLOBAL_POOL
        - WORKER_POOL_CAPACITY=16
    ports:
      - "4567:4567"
      - "9010:9010"
    networks:
      - my_network

networks:
   my_network:


