version: '2'
services:
  db:
    build: ./postgres
    environment:
        - DB_NAME=mydb
    expose:
      - "5432"
    volumes:
       - db_data:/var/lib/postgresql/data
    networks:
      my_network:
        aliases:
          - mydb
  httpServer:
    image: maven:3-alpine
    command: mvn exec:java
    depends_on:
      - db
    volumes:
        - .:/opt/app
        - maven_repo:/root/.m2
    working_dir: /opt/app
    environment:
        - MAVEN_OPTS= -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Xms128m -Xmx128m
        - APP_STRATEGY=GLOBAL_POOL
        - WORKER_POOL_CAPACITY=16
    ports:
      - "4567:4567"
      - "9010:9010"
    networks:
      - my_network
    memswap_limit: 512M
    mem_limit: 512M

networks:
   my_network:

volumes:
   db_data:
   maven_repo:

